### PR TITLE
Add logging to file

### PR DESCRIPTION
**Pull request by atrepca**
This is to add logging to file and move the credentials file to a dot file (security through obscurity), both in the running user's home directory.

### CODE REVIEW

**Comment by atrepca** [comment]
@mconigliaro Does this make sense?

**Comment by mconigliaro** [comment]
Sorry for the late reply. This seems OK, but I have to admit I haven't used this project in years. Any interest in taking it over?

**Comment by atrepca** [comment]
Thanks for the proposal, I guess I could find the time for it. What did you have in mind?

**Comment by mconigliaro** [comment]
If you're interested, I can just transfer ownership of the repo and the ruby gems to you.

**Comment by atrepca** [comment]
Let's do it.

**Pull request merged**
